<!-- <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 col-md-offset-3"> -->
<h2>Pagination</h2>
<table class="table table-hover table-bordered">
    <tbody>
        <tr>
            <th width="25%">Username</th>
            <th>Fullname</th>
            <th>Email</th>
        </tr>
        <?php if (count($this->paginator)): ?>
        <?php foreach ($this->paginator as $user):?>
        <tr>
            <td><?= $this->escapeHtml($user->getUsername()); ?></td>
            <td><?= $this->escapeHtml($user->getFullname()); ?></td>
            <td><?= $this->escapeHtml($user->getEmail()); ?></td>
        </tr>
        <?php endforeach ?>
        <?php endif; ?>
    </tbody>
</table>
<?php echo $this->paginationControl($this->paginator,
'All',
'paginator/paginator-2.phtml', array('route' => 'paginator')); ?>

</div>
<!-- </div> -->
