<?php
$this->headTitle('Sign in');

?>

<div class="row">
    <div class="col-md-offset-3 col-md-6">
        <form class="form-horizontal" method="post" >
            <h2 class="form-signin-heading">Please sign in</h2>
            <?php if ($isLoginError): ?>
                <div class="alert alert-warning" role="alert">
                    Incorrect login and/or password. 
                    <a href="<?= $this->url('reset-password') ?>">Forgot password?</a>
                </div>
            <?php endif; ?>
            <div class="form-group">
            <?= $this->formLabel($form->get('email')); ?>
                
                <div class="col-xs-9 col-sm-9 col-md-9 col-lg-9">
                    <?= $this->formElement($form->get('email')); ?>
                </div>
            </div>
            <div class="form-group">
                <?= $this->formLabel($form->get('password')); ?>
                <div class="col-xs-9 col-sm-9 col-md-9 col-lg-9">
                    <?= $this->formElement($form->get('password')); ?>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-6 col-sm-offset-3">
                    <?= $this->formElement($form->get('remember_me')); ?>
                    <?= $this->formLabel($form->get('remember_me')); ?>
                </div>
            </div>
            
            <?= $this->formElement($form->get('redirect_url')); ?>
            <?= $this->formElement($form->get('csrf')) ?>
            <div class="form-group"> 	
                <div class="col-sm-6 col-sm-offset-3">
                    <?= $this->formElement($form->get('submit')); ?>
                </div>
            </div>
            
        </form>
    </div>
</div>