<?php
$this->headTitle('Add User');

$form->prepare();
?>

<h1>Add User</h1>


<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <?= $this->form()->openTag($form); ?>
        <div class="form-group">
            <?= $this->formLabel($form->get('username')); ?>
            <div class="col-sm-9">
                <?= $this->formElement($form->get('username')); ?>
                <?= $this->formElementErrors($form->get('username')); ?>   
            </div>               
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('fullname')); ?>
            <div class="col-sm-9">
                <?= $this->formElement($form->get('fullname')); ?>
                <?= $this->formElementErrors($form->get('fullname')); ?>   
            </div>               
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('birthdate')); ?>
            <div class="col-sm-9">
                <?= $this->formElement($form->get('birthdate')); ?>
                <?= $this->formElementErrors($form->get('birthdate')); ?> 
            </div>                 
        </div>
        <div class="form-group">
            <?= $this->formLabel($form->get('gender')); ?>
            <div class="col-sm-9">
                <?= $this->formElement($form->get('gender')); ?>
                <?= $this->formElementErrors($form->get('gender')); ?> 
            </div>                 
        </div>
        <div class="form-group">
            <?= $this->formLabel($form->get('address')); ?>
            <div class="col-sm-9">
                <?= $this->formElement($form->get('address')); ?>
                <?= $this->formElementErrors($form->get('address')); ?>   
            </div>               
        </div>
        
        
        <div class="form-group">
            <?= $this->formLabel($form->get('email')); ?>
            <div class="col-sm-9">
                <?= $this->formElement($form->get('email')); ?>
                <?= $this->formElementErrors($form->get('email')); ?>     
            </div>             
        </div>
        <div class="form-group">
            <?= $this->formLabel($form->get('phone')); ?>
            <div class="col-sm-9">
                <?= $this->formElement($form->get('phone')); ?>
                <?= $this->formElementErrors($form->get('phone')); ?> 
            </div>                
        </div>
        
        
        <div class="form-group">
            <?= $this->formLabel($form->get('password')); ?>
            <div class="col-sm-9">
                <?= $this->formElement($form->get('password')); ?>
                <?= $this->formElementErrors($form->get('password')); ?>   
            </div>               
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('confirm_password')); ?>
            <div class="col-sm-9">
                <?= $this->formElement($form->get('confirm_password')); ?>
                <?= $this->formElementErrors($form->get('confirm_password')); ?> 
            </div>                 
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('roles')); ?>
            <div class="col-sm-9">
                <?= $this->formElement($form->get('roles')); ?>
                <?= $this->formElementErrors($form->get('roles')); ?> 
            </div>                 
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('status')); ?>
            <div class="col-sm-9">
                <?= $this->formElement($form->get('status')); ?>
                <?= $this->formElementErrors($form->get('status')); ?>
            </div>                 
        </div>
        
        <div class="form-group">
            <div class="col-sm-6 col-md-offset-3">
                <?= $this->formElement($form->get('submit')); ?>
            </div>
        </div>
        <?= $this->form()->closeTag(); ?>
    </div>    
</div>   

