<?php
$this->headTitle('Set New Password');

$form->prepare();
?>

<div class="row">
    <div class="col-md-offset-3 col-md-6">
        <?= $this->form()->openTag($form); ?>

        <h2>Set New Password</h2>

        <p>Enter your new password in the form below</p>

        <div class="form-group">
            <?= $this->formLabel($form->get('new_password')); ?>
            <div class="col-sm-9">
                <?= $this->formElement($form->get('new_password')); ?>
                <?= $this->formElementErrors($form->get('new_password')); ?>   
            </div>               
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('confirm_new_password')); ?>
            <div class="col-sm-9">
                <?= $this->formElement($form->get('confirm_new_password')); ?>
                <?= $this->formElementErrors($form->get('confirm_new_password')); ?> 
            </div>                 
        </div>   
            
        <?= $this->formElement($form->get('submit')); ?>

        <?= $this->formElement($form->get('csrf')); ?>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>

