<?php
$this->headTitle('Change Password');

$form->prepare();
?>

<h1>Change Password</h1>

<div class="col-md-6 col-md-offset-3">
    <?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
</div>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <?= $this->form()->openTag($form); ?>
        <?= $this->formElement($form->get('csrf')); ?>

        <div class="form-group">
            <?= $this->formLabel($form->get('old_password')); ?>
            <div class="col-sm-9">
                <?= $this->formElement($form->get('old_password')); ?>
                <?= $this->formElementErrors($form->get('old_password')); ?>   
            </div>               
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('new_password')); ?>
            <div class="col-sm-9">
                <?= $this->formElement($form->get('new_password')); ?>
                <?= $this->formElementErrors($form->get('new_password')); ?>   
            </div>               
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('confirm_new_password')); ?>
            <div class="col-sm-9">
                <?= $this->formElement($form->get('confirm_new_password')); ?>
                <?= $this->formElementErrors($form->get('confirm_new_password')); ?> 
            </div>                 
        </div>
        
        <div class="form-group">
            <div class="col-sm-6 col-md-offset-3">
                <?= $this->formElement($form->get('submit')); ?>
            </div>
        </div>
        <?= $this->form()->closeTag(); ?>
    </div>    
</div>   

