<?php
$title = 'Delete User';
$url   = $this->url('user', ['action' => 'delete', 'id' => $user->id]);

$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>

<p>
    Bạn có chắc chắn muốn xóa tài khoản
    "<?= $this->escapeHtml($user->username) ?>" 
</p>

<form action="<?= $url ?>" method="post">
<div class="form-group">
    <input type="hidden" name="id" value="<?= (int) $user->id ?>" />
    <input type="submit" class="btn btn-danger" name="del" value="Yes" />
    <input type="submit" class="btn btn-success" name="del" value="No" />
</div>
</form>
