<h1>Users</h1>
<div class="col-md-6 col-md-offset-3">
  <?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
</div>
<table class="table table-hover">

    <thead>
      <tr>
        <th>Username</th>
        <th>Fullname</th>
        <th>Address</th>
        <th>Email</th>
        <th>Roles</th>
        <th>Action</th>
      </tr>
    </thead>  
    <tbody>
    
      <?php foreach ($users as $user): ?>
        <tr>
          <td><?= $user->username; ?></td>
          <td><?= $user->fullname; ?></td>
          <td><?= $user->address; ?></td>
          <td><?= $user->email; ?></td>
          <td><?= $user->role; ?></td>
          <td>
          <a class="btn btn-info" href="<?= $this->url('user', 
                    ['action'=>'edit', 'id'=>$user->id]); ?>">
                <span class="glyphicon glyphicon-pencil" ></span> Edit
            </a>
            <a class="btn btn-primary" href="<?= $this->url('user',
                    ['action'=>'change-password', 'id'=>$user->id]); ?>">
                <span class="glyphicon glyphicon-pencil"></span> Đối mật khẩu
            </a>
            <a class="btn btn-default" href="<?= $this->url('user',
                    ['action'=>'delete', 'id'=>$user->id]); ?>">
                <span class="glyphicon glyphicon-asterisk"></span> Xóa
            </a>
          </td>
        </tr>
      <?php endforeach ?>
    </tbody>
</table>
